### ISSUE TITLE
Add option to ignore downloads

### ISSUE THREAD

**Issue by ZryletTC** [goerz/doctr_versions_menu#4]
* doctr_versions_menu version: 0.2.0
* Python version: 3.6.7
* Operating System: linux, xenial

### Description

Hi!

Thanks for putting this together. I've implemented it in a test project and it seems to work very nicely. I'm planning on including it in a bunch of our repositories at @pcdshub :)

There was one feature I would like to request. We typically don't create any artifacts for download and don't really intend to anytime soon. Because of this, our build creates a bunch of warnings about not finding `_downloads` folders. Could you add in a little configuration value or command line argument to skip looking for downloads?

Probably should put in a separate issue but I also just noticed that this build did not commit its `version.py`. Is this intended?

Thanks,
Tyler

### What I Did

The full build can be seen at https://travis-ci.com/github/hhslepicka/testproject1234/jobs/332155166. Lines of interest are [445-451](https://travis-ci.com/github/hhslepicka/testproject1234/jobs/332155166#L445-L451) and [556](https://travis-ci.com/github/hhslepicka/testproject1234/jobs/332155166#L556).

**Comment by goerz** [comment]
Sure, I can suppress the warning if `--downloads-file` is given as empty (or `downloads_file` is set to `None` in the settings file). It's purely a cosmetic issue, but I see your point.

The missing `versions.py` is a bug, though (#5)

**Comment by goerz** [comment]
You should now be able to put

~~~
downloads_file = False
~~~

in the `doctr-versions-menu.conf`. Note that `None` as I originally proposed does not work, due to some internals of [`click`](https://click.palletsprojects.com/en/7.x/).

Let me know if that works for you, and if you're running into other issues, and I'll release this as `v0.3.0`.

**Comment by goerz** [comment]
Also, if you end up using it for any publicly available packages, feel free to open a PR to add them to the list of [Examples](https://github.com/goerz/doctr_versions_menu#examples) in the [README.rst](https://github.com/goerz/doctr_versions_menu/edit/master/README.rst)

**Comment by ZryletTC** [comment]
Great, thanks for adding that!
It'll likely take awhile before I get a chance to add it to a public repo but I'll definitely add to the list when I do 👍
