### ISSUE TITLE
Allow configuration in sphinx's conf.py

### ISSUE THREAD

**Issue by ZryletTC** [goerz/doctr_versions_menu#7]
An alternative to #6 but also just a separate desired feature, would it be possible for doctr-versions-menu to support pulling configuration values from sphinx's `conf.py` as other extensions do?

Obviously, neither of these requests are urgent as the tool works fine already. Just things I noticed would be nice to have. Maybe I'll take a stab at this one if I get around to it :)

**Comment by goerz** [comment]
No, that won't work. The `conf.py` file is executed in the context of a Sphinx run and typically has a lot of side effects. Only Sphinx extensions should use it for configuration, and in fact the Sphinx-extension-part of Doctr Versions Menu [does](https://goerz.github.io/doctr_versions_menu/v0.2.0/sphinx_extension.html#customization).

However, the settings for the `doct-versions-conf` executable that runs during deployment can't reasonably get config options from `conf.py`.
